import { chmodSync, writeFileSync } from "node:fs";

function credentialLine(name, value) {
  return value ? `${name}=${value}\n` : "";
}

export function bankLink(baseUrl, startToken) {
  // Fragment, not query: the token must never appear in a request URL, where
  // Cloudflare's invocation logs and proxies would record it. The /auth/start
  // page exchanges it for a short-lived cookie over POST.
  return `${baseUrl.replace(/\/$/, "")}/auth/start#k=${encodeURIComponent(startToken)}`;
}

/** Persist client-facing secrets locally and emit only a safe pointer to stdout. */
export function writeClientCredentials({
  filePath,
  mcpSecret,
  startToken,
  localUrl,
  cloudUrl,
  mode,
  stdout = (line) => console.log(line),
}) {
  const preferredUrl = cloudUrl || localUrl;
  const body = [
    "# Generated by banking-mcp setup. Keep this file private.\n",
    credentialLine("MCP_URL", `${preferredUrl.replace(/\/$/, "")}/mcp`),
    credentialLine("CONNECTION_PASSWORD", mcpSecret),
    credentialLine("BANK_LINK", bankLink(preferredUrl, startToken)),
    mode === "local" || mode === "both"
      ? credentialLine("LOCAL_MCP_URL", `${localUrl.replace(/\/$/, "")}/mcp`)
      : "",
    (mode === "cloud" || mode === "both") && cloudUrl
      ? credentialLine("CLOUD_MCP_URL", `${cloudUrl.replace(/\/$/, "")}/mcp`)
      : "",
  ].join("");

  writeFileSync(filePath, body, { mode: 0o600 });
  // writeFileSync's mode does not tighten an already-existing file.
  chmodSync(filePath, 0o600);
  stdout(`Client credentials were written to ${filePath}. Open that file locally.`);
  return filePath;
}
