import { chmodSync, writeFileSync } from "node:fs";

function credentialLine(name, value) {
  return value ? `${name}=${value}\n` : "";
}

export function bankLink(baseUrl, startToken, { bank, psu, country } = {}) {
  // Fragment, not query: the token must never appear in a request URL, where
  // Cloudflare's invocation logs and proxies would record it. The /auth/start
  // page exchanges it for a short-lived cookie over POST. The bank name and
  // account type ride in the query so /auth/start can start the session for
  // the bank the operator already linked in the Enable Banking Control Panel.
  const base = baseUrl.replace(/\/$/, "");
  const params = new URLSearchParams();
  if (psu) params.set("psu", psu);
  if (bank) params.set("bank", bank);
  if (country) params.set("country", country);
  const query = params.toString();
  return `${base}/auth/start${query ? `?${query}` : ""}#k=${encodeURIComponent(startToken)}`;
}

/** Persist client-facing secrets locally and emit only a safe pointer to stdout. */
export function writeClientCredentials({
  filePath,
  mcpSecret,
  localUrl,
  cloudUrl,
  mode,
  stdout = (line) => console.log(line),
}) {
  const preferredUrl = cloudUrl || localUrl;
  const body = [
    "# Generated by banking-mcp setup. Keep this file private.\n",
    credentialLine("MCP_URL", `${preferredUrl.replace(/\/$/, "")}/mcp`),
    credentialLine("CONNECTION_PASSWORD", mcpSecret),
    mode === "local" || mode === "both"
      ? credentialLine("LOCAL_MCP_URL", `${localUrl.replace(/\/$/, "")}/mcp`)
      : "",
    (mode === "cloud" || mode === "both") && cloudUrl
      ? credentialLine("CLOUD_MCP_URL", `${cloudUrl.replace(/\/$/, "")}/mcp`)
      : "",
    // The operator token is not written here; it stays in .dev.vars, which
    // auth:link reads to print a bank link on demand.
    "# Connect a bank: run 'npm run auth:link -- --bank=<ASPSP name>' on the operator machine.\n",
  ].join("");

  writeFileSync(filePath, body, { mode: 0o600 });
  // writeFileSync's mode does not tighten an already-existing file.
  chmodSync(filePath, 0o600);
  stdout(`Client credentials were written to ${filePath}. Open that file locally.`);
  return filePath;
}
